# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qhar_main.ui'
#
# Created: Thu Dec 11 11:26:43 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(611, 387)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.stackedWidget_main = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget_main.setObjectName(_fromUtf8("stackedWidget_main"))
        self.page_week = QtGui.QWidget()
        self.page_week.setObjectName(_fromUtf8("page_week"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.page_week)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tableWidget_week = QtGui.QTableWidget(self.page_week)
        self.tableWidget_week.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_week.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_week.setAutoScroll(False)
        self.tableWidget_week.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_week.setDragDropOverwriteMode(False)
        self.tableWidget_week.setAlternatingRowColors(True)
        self.tableWidget_week.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_week.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_week.setCornerButtonEnabled(False)
        self.tableWidget_week.setRowCount(7)
        self.tableWidget_week.setColumnCount(8)
        self.tableWidget_week.setObjectName(_fromUtf8("tableWidget_week"))
        self.tableWidget_week.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_week.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_week.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.tableWidget_week)
        self.stackedWidget_main.addWidget(self.page_week)
        self.page_view = QtGui.QWidget()
        self.page_view.setObjectName(_fromUtf8("page_view"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.page_view)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tableWidget_view = QtGui.QTableWidget(self.page_view)
        self.tableWidget_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_view.setAutoScroll(False)
        self.tableWidget_view.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_view.setDragDropOverwriteMode(False)
        self.tableWidget_view.setAlternatingRowColors(True)
        self.tableWidget_view.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_view.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_view.setCornerButtonEnabled(False)
        self.tableWidget_view.setRowCount(0)
        self.tableWidget_view.setColumnCount(8)
        self.tableWidget_view.setObjectName(_fromUtf8("tableWidget_view"))
        self.tableWidget_view.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_view.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_view.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.tableWidget_view, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_filter = QtGui.QLabel(self.page_view)
        self.label_filter.setObjectName(_fromUtf8("label_filter"))
        self.horizontalLayout_2.addWidget(self.label_filter)
        self.comboBox_filter = QtGui.QComboBox(self.page_view)
        self.comboBox_filter.setObjectName(_fromUtf8("comboBox_filter"))
        self.horizontalLayout_2.addWidget(self.comboBox_filter)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_select = QtGui.QPushButton(self.page_view)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("dialog-ok-apply"))
        self.pushButton_select.setIcon(icon)
        self.pushButton_select.setObjectName(_fromUtf8("pushButton_select"))
        self.horizontalLayout_2.addWidget(self.pushButton_select)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.stackedWidget_main.addWidget(self.page_view)
        self.gridLayout_2.addWidget(self.stackedWidget_main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setObjectName(_fromUtf8("menu_Settings"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_Go = QtGui.QMenu(self.menubar)
        self.menu_Go.setObjectName(_fromUtf8("menu_Go"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.listWidget_log = QtGui.QListWidget(self.dockWidgetContents)
        self.listWidget_log.setObjectName(_fromUtf8("listWidget_log"))
        self.gridLayout.addWidget(self.listWidget_log, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.action_Open = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.action_Open.setIcon(icon)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Save = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.action_Save.setIcon(icon)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_SaveAs = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save-as"))
        self.action_SaveAs.setIcon(icon)
        self.action_SaveAs.setObjectName(_fromUtf8("action_SaveAs"))
        self.action_Quit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.action_Quit.setIcon(icon)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_About = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("system-help"))
        self.action_About.setIcon(icon)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.action_Settings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("preferences-system"))
        self.action_Settings.setIcon(icon)
        self.action_Settings.setObjectName(_fromUtf8("action_Settings"))
        self.action_Print = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-print"))
        self.action_Print.setIcon(icon)
        self.action_Print.setObjectName(_fromUtf8("action_Print"))
        self.action_Edit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-properties"))
        self.action_Edit.setIcon(icon)
        self.action_Edit.setObjectName(_fromUtf8("action_Edit"))
        self.action_This_week = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("x-office-calendar"))
        self.action_This_week.setIcon(icon)
        self.action_This_week.setObjectName(_fromUtf8("action_This_week"))
        self.action_Previous_week = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-previous"))
        self.action_Previous_week.setIcon(icon)
        self.action_Previous_week.setObjectName(_fromUtf8("action_Previous_week"))
        self.action_Next_week = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-next"))
        self.action_Next_week.setIcon(icon)
        self.action_Next_week.setObjectName(_fromUtf8("action_Next_week"))
        self.action_Import = QtGui.QAction(MainWindow)
        self.action_Import.setObjectName(_fromUtf8("action_Import"))
        self.action_Export = QtGui.QAction(MainWindow)
        self.action_Export.setObjectName(_fromUtf8("action_Export"))
        self.action_New = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-new"))
        self.action_New.setIcon(icon)
        self.action_New.setObjectName(_fromUtf8("action_New"))
        self.action_Replace = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("view-refresh"))
        self.action_Replace.setIcon(icon)
        self.action_Replace.setObjectName(_fromUtf8("action_Replace"))
        self.action_Add = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.action_Add.setIcon(icon)
        self.action_Add.setObjectName(_fromUtf8("action_Add"))
        self.action_View = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("text-x-generic"))
        self.action_View.setIcon(icon)
        self.action_View.setObjectName(_fromUtf8("action_View"))
        self.action_Remove = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-remove"))
        self.action_Remove.setIcon(icon)
        self.action_Remove.setObjectName(_fromUtf8("action_Remove"))
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.action_SaveAs)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Import)
        self.menu_File.addAction(self.action_Export)
        self.menu_File.addAction(self.action_Print)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_Help.addAction(self.action_About)
        self.menu_Settings.addAction(self.action_Settings)
        self.menu_Edit.addAction(self.action_Add)
        self.menu_Edit.addAction(self.action_Remove)
        self.menu_Edit.addAction(self.action_Edit)
        self.menu_Edit.addAction(self.action_Replace)
        self.menu_Go.addAction(self.action_Previous_week)
        self.menu_Go.addAction(self.action_Next_week)
        self.menu_Go.addAction(self.action_This_week)
        self.menu_Go.addAction(self.action_View)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Go.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.action_New)
        self.toolBar.addAction(self.action_Open)
        self.toolBar.addAction(self.action_Save)
        self.toolBar.addAction(self.action_Print)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Add)
        self.toolBar.addAction(self.action_Remove)
        self.toolBar.addAction(self.action_Edit)
        self.toolBar.addAction(self.action_Replace)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Previous_week)
        self.toolBar.addAction(self.action_Next_week)
        self.toolBar.addAction(self.action_This_week)
        self.toolBar.addAction(self.action_View)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Settings)

        self.retranslateUi(MainWindow)
        self.stackedWidget_main.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tableWidget_view.setSortingEnabled(True)
        self.label_filter.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButton_select.setText(_translate("MainWindow", "PushButton", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.menu_Settings.setTitle(_translate("MainWindow", "&Settings", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menu_Go.setTitle(_translate("MainWindow", "&Go", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Logger", None))
        self.action_Open.setText(_translate("MainWindow", "&Open ...", None))
        self.action_Save.setText(_translate("MainWindow", "&Save", None))
        self.action_SaveAs.setText(_translate("MainWindow", "Save &as ...", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_About.setText(_translate("MainWindow", "&About", None))
        self.action_Settings.setText(_translate("MainWindow", "&Settings ...", None))
        self.action_Print.setText(_translate("MainWindow", "&Print", None))
        self.action_Edit.setText(_translate("MainWindow", "&Edit selected recipe", None))
        self.action_Edit.setToolTip(_translate("MainWindow", "Edit selected recipe", None))
        self.action_This_week.setText(_translate("MainWindow", "&This week", None))
        self.action_Previous_week.setText(_translate("MainWindow", "&Previous week", None))
        self.action_Next_week.setText(_translate("MainWindow", "&Next week", None))
        self.action_Import.setText(_translate("MainWindow", "I&mport ...", None))
        self.action_Export.setText(_translate("MainWindow", "E&xport ...", None))
        self.action_New.setText(_translate("MainWindow", "New", None))
        self.action_Replace.setText(_translate("MainWindow", "Replace &selected item", None))
        self.action_Replace.setToolTip(_translate("MainWindow", "Replace selected item", None))
        self.action_Add.setText(_translate("MainWindow", "&Add new recipe ...", None))
        self.action_Add.setToolTip(_translate("MainWindow", "Add new recipe", None))
        self.action_View.setText(_translate("MainWindow", "&View recipe list", None))
        self.action_View.setToolTip(_translate("MainWindow", "View recipe list", None))
        self.action_Remove.setText(_translate("MainWindow", "&Remove selected recipe ...", None))

